### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by ge0rdi**
First of all I'd like to appreciate great work you did on Videodevil (hopefully it will be merged soon) :thumbsup:

Here is a patch that greatly improves performance of video list processing. Especially on slow devices (on my RPi list of videos for certain site took about 30s, after patch it was about 6s).

The biggest problem was in _clean1()_ and _decode()_. They in fact do the same thing and both were suboptimal.
I have also rearranged couple of things and removed unnecessary tables. I believe it should produce the same result as original code.

### CODE REVIEW

**Comment by joedev1981** [comment]
Awesome, I recently picked up on this as well.  Please check out my latest version.  I don't think changes this be will ever make it into the official release but I am hopeful.  Sorry this took so long me find.  I am still learning about all this development stuff.  I experiment alot with this repository and when I get to the point where I like the result I put it on my own/separate github repository.  I would like to keep them all in one place but I kept messing things up and this is what final seems to be working.  Once I get more familiar with everything I will keep everything in this fork.

Going to check out your fixes, from the way you code I can tell your much better than I am at it.  Hopefully its faster than my latest, I want to squeeze all inefficiencies out of this project. (btw, my goal is to get this working reasonably fast on the slowest machines!) 
Thanks for your help and input.  Until recently I wasn't aware of anyone using my experimental versions.  You can post comments and suggestions on my new thread at http://forum.xbmc.org/showthread.php?tid=191958.

**Comment by joedev1981** [comment]
Please look at line 25:
        o = smart_unicode(o)
I think it should be:
        o = smart_unicode(s)
The try statement silences the error.  Going to time it with this change.

**Comment by ge0rdi** [comment]
Thank you, it should be fixed by now (I'm just wondering why I haven't noticed that during testing).

I've also tested your latest version and it works awesome. Even on my RPi it is very fast.

**Comment by joedev1981** [comment]
Can you created a new pull request for this in  joedev1981:experimental.  The website says it can't be automatically merged.  it gives command line option but I mess things up quickly and prefer to do this right the first time instead of messing up the commit history.

**Comment by ge0rdi** [comment]
I've rebased my branch to your experimental. Now you should be able to merge it.

**Comment by joedev1981** [comment]
Done, thanks

**Pull request merged**
